# Generated by Django 2.2.4 on 2019-08-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0106_django_prices_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_field',
            field=models.TextField(blank=True, default='Custom field'),
        ),
    ]
