# Generated by Django 2.2.4 on 2019-08-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0107_category_custom_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='custom_field',
            new_name='testCustomField',
        ),
    ]
